### ISSUE TITLE
parent issue: Add namespace functionality to VID

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/jellyfish#358]
- [ ] EspressoSystems/hotshot-primitives#72 
- [ ] EspressoSystems/hotshot-primitives#73 
- [ ] snark-friendly completeness proof for an entire namespace
  - Do we also want a native (non-snark) implementation?
